#!/bin/sh

yadm remote set-url origin "git@github.com:morten-b/sway-dotfiles.git"

sudo pacman -Syu --noconfirm - < $HOME/.config/yadm/pacman.lst

yay -Syu --noconfirm - < $HOME/.config/yadm/aur.lst

chsh -s /usr/bin/fish
