#!/bin/sh

yadm remote set-url origin "git@github.com:morten-b/sway-dotfiles.git"

sudo pacman -Syu --noconfirm --needed - < $HOME/.config/yadm/pacman.lst

yay -Syu --noconfirm - < $HOME/.config/yadm/aur.lst

# default shell
#chsh -s /usr/bin/fish

sudo nextdns install -config 2a7136 -report-client-info -auto-activate

# https://wiki.archlinux.org/index.php/getty
sudo mkdir /etc/systemd/system/getty@tty1.service.d/
sudo cp $HOME/.config/autologin /etc/systemd/system/getty@tty1.service.d/override.conf

reboot
